// Barrel — reexporta tudo que dashShared.jsx expunha antes da divisão
export { toPascal, toKebab, LucideIcon, getAllIcons } from './icons'
export { fmtNum, isNumCol, fmtInterval, isStatusCol, corStatusValor } from './format'
export { TIPOS, PALETA, INTERVALOS, FILL_HEIGHT_TIPOS, isFillHeight } from './constants'
export { SQL_HINTS, SQL_GUIDE } from './sqlGuide'
export { WidgetBody } from './chartTypes/WidgetBody'
export { WidgetCard } from './WidgetCard'
export { WidgetGrid } from './WidgetGrid'
export { useDashboardWidgets } from './useDashboardWidgets'
export { runWidgetQuery } from './runWidgetQuery'
export { WidgetForm, Label } from './WidgetForm'
export { IconPicker } from './IconPicker'
